[package]
name        = "cw20-icg-pkg"
version     = "0.1.0"
authors     = ["Rhaki"]
edition     = "2021"
description = "Package for cw20-icg"
license     = "Apache-2.0"
repository  = "https://github.com/Rhaki/inter-chain-gate-core"

[dependencies]
gate-pkg        = { path = "../gate", version = "0.1.0" }
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
serde           = { workspace = true }
cw20            = { workspace = true }
cw20-base       = { workspace = true }


