[package]
name = "gate-pkg"
version = "0.1.0"
authors = ["Rhaki"]
edition = "2021"
description = "Package for interchain-gate-core"
license = "Apache-2.0"
repository = "https://github.com/Rhaki/inter-chain-gate-core"

[dependencies]
cosmwasm-schema = { version = "1.1.0" }
cosmwasm-std = {version = "1.1.0"}
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
cw20 = "1.0.1"

[features]
gate = []

