[package]
name        = "gate-pkg"
version     = "0.1.0"
authors     = ["Rhaki"]
edition     = "2021"
description = "Package for interchain-gate-core"
license     = "Apache-2.0"
repository  = "https://github.com/Rhaki/inter-chain-gate-core"

[features]
gate = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }
serde           = { workspace = true }
cw20            = { workspace = true }
account-icg-pkg = { path = "../account-icg", version = "0.1.0" }


